-- Customer usernames, private profile photos, and verified meal ratings.
alter table public.customers
  add column if not exists username text,
  add column if not exists avatar_path text,
  add column if not exists delivery_address text,
  add column if not exists delivery_area text,
  add column if not exists delivery_latitude double precision,
  add column if not exists delivery_longitude double precision;

create unique index if not exists customers_username_lower_unique_idx
  on public.customers (lower(username))
  where username is not null and username <> '';

do $$
begin
  if not exists (
    select 1 from public.customers
    where email is not null and email <> ''
    group by lower(email) having count(*) > 1
  ) then
    create unique index if not exists customers_email_lower_unique_idx
      on public.customers (lower(email))
      where email is not null and email <> '';
  end if;
end $$;

alter table public.orders
  add column if not exists customer_id bigint references public.customers(id) on delete set null;
create index if not exists orders_customer_id_idx on public.orders (customer_id);

-- Link older guest orders to an account when the account uses the same saved phone.
update public.orders as o
set customer_id = c.id
from public.customers as c
where o.customer_id is null and o.customer_phone = c.phone;

create table if not exists public.meal_reviews (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  meal_id bigint not null references public.meals(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, meal_id)
);
create index if not exists meal_reviews_meal_id_idx on public.meal_reviews (meal_id);
alter table public.meal_reviews enable row level security;
drop policy if exists "Service role manages meal reviews" on public.meal_reviews;
create policy "Service role manages meal reviews" on public.meal_reviews for all using (false);

insert into storage.buckets (id, name, public)
values ('customer-avatars', 'customer-avatars', false)
on conflict (id) do update set public = false;

-- The profile-photo bucket is private, including for users with other storage policies.
drop policy if exists "Keep customer avatars private" on storage.objects;
create policy "Keep customer avatars private"
  on storage.objects as restrictive for all to anon, authenticated
  using (bucket_id <> 'customer-avatars')
  with check (bucket_id <> 'customer-avatars');
