-- Customer accounts for order history and sign-in.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  email text,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.customers enable row level security;

drop policy if exists "Service role manages customers" on public.customers;

create policy "Service role manages customers"
on public.customers for all
using (false);
