-- Expanded Vegetables & Greens catalog, split into supermarket-style subcategories.
insert into public.products (id, name, description, category, section, unit, price, image, stock_status)
values
  ('fresh-tomatoes', 'Tomatoes', 'Fresh tomatoes for sauces, stews, and salads.', 'Tomatoes', 'fresh-food', '1 kg', 3500, '🍅', 'in_stock'),
  ('fresh-cherry-tomatoes', 'Cherry Tomatoes', 'Small, sweet tomatoes for salads and snacking.', 'Tomatoes', 'fresh-food', '1 pack', 2500, '🍅', 'in_stock'),
  ('fresh-onions', 'Onions', 'Crisp onions for everyday cooking.', 'Onions & Aromatics', 'fresh-food', '1 kg', 2800, '🧅', 'in_stock'),
  ('fresh-red-onion', 'Red Onion', 'Sharp, colourful onion for salads and stews.', 'Onions & Aromatics', 'fresh-food', '1 kg', 3000, '🧅', 'in_stock'),
  ('fresh-spring-onion', 'Spring Onion', 'Mild, fresh onion greens for garnish and stir-fry.', 'Onions & Aromatics', 'fresh-food', '1 bunch', 800, '🧅', 'in_stock'),
  ('fresh-shallots', 'Shallots', 'Small, mild onions with a delicate flavour.', 'Onions & Aromatics', 'fresh-food', '1 pack', 1500, '🧅', 'in_stock'),
  ('fresh-ginger', 'Fresh Ginger', 'Aromatic root for seasoning, drinks, and cooking.', 'Onions & Aromatics', 'fresh-food', '1 kg', 2000, '🫚', 'in_stock'),
  ('fresh-garlic', 'Fresh Garlic', 'Everyday aromatic used in most Nigerian dishes.', 'Onions & Aromatics', 'fresh-food', '1 kg', 2500, '🧄', 'in_stock'),
  ('fresh-ugu', 'Ugu Leaves (Ugwu)', 'Fresh fluted pumpkin leaves for soups.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1200, '🌿', 'in_stock'),
  ('fresh-waterleaf', 'Waterleaf', 'Soft, leafy green used in soups and stews.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-bitterleaf', 'Bitter Leaf', 'Traditional bitter leaf, washed or unwashed, for soup.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1200, '🌿', 'in_stock'),
  ('fresh-ewedu', 'Ewedu', 'Jute leaves for the classic ewedu soup.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-uziza', 'Uziza Leaves', 'Peppery leaves used to season soups.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-oha-leaves', 'Oha Leaves', 'Traditional leaves for Oha soup.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 1500, '🌿', 'in_stock'),
  ('fresh-afang-leaves', 'Afang Leaves', 'Shredded afang leaves for Afang soup.', 'Nigerian Local Greens', 'fresh-food', '1 bunch', 2000, '🌿', 'in_stock'),
  ('fresh-plantain', 'Ripe Plantain', 'Sweet ripe plantain for frying and cooking.', 'Plantain & Cooking Banana', 'fresh-food', '1 kg', 3000, '🍌', 'in_stock'),
  ('fresh-unripe-plantain', 'Unripe Plantain', 'Firm, green plantain for boiling and porridge.', 'Plantain & Cooking Banana', 'fresh-food', '1 kg', 2800, '🍌', 'in_stock'),
  ('fresh-cooking-banana', 'Cooking Banana', 'Starchy banana variety used for cooking.', 'Plantain & Cooking Banana', 'fresh-food', '1 kg', 2000, '🍌', 'in_stock'),
  ('fresh-carrot', 'Carrots', 'Crisp, sweet carrots for cooking and salads.', 'Roots & Tubers', 'fresh-food', '1 kg', 1500, '🥕', 'in_stock'),
  ('fresh-beetroot', 'Beetroot', 'Earthy root vegetable for salads and juice.', 'Roots & Tubers', 'fresh-food', '1 kg', 2000, '🥔', 'in_stock'),
  ('fresh-radish', 'Radish', 'Crunchy, peppery root for salads.', 'Roots & Tubers', 'fresh-food', '1 kg', 1500, '🥔', 'in_stock'),
  ('fresh-turnip', 'Turnip', 'Mild root vegetable for soups and stews.', 'Roots & Tubers', 'fresh-food', '1 kg', 1500, '🥔', 'in_stock'),
  ('fresh-sweet-potato', 'Sweet Potato', 'Naturally sweet tuber, boiled, fried, or roasted.', 'Roots & Tubers', 'fresh-food', '1 kg', 1800, '🍠', 'in_stock'),
  ('fresh-green-cabbage', 'Green Cabbage', 'Crisp cabbage for salads, stir-fry, and stews.', 'Leafy Greens', 'fresh-food', '1 piece', 1200, '🥬', 'in_stock'),
  ('fresh-red-cabbage', 'Red Cabbage', 'Colourful cabbage for salads and slaw.', 'Leafy Greens', 'fresh-food', '1 piece', 1500, '🥬', 'in_stock'),
  ('fresh-spinach', 'Spinach', 'Tender spinach leaves for soups and side dishes.', 'Leafy Greens', 'fresh-food', '1 bunch', 1200, '🥬', 'in_stock'),
  ('fresh-green-bell-pepper', 'Green Bell Pepper', 'Mild, crisp pepper for stews and stir-fry.', 'Peppers', 'fresh-food', '1 kg', 2000, '🫑', 'in_stock'),
  ('fresh-red-bell-pepper', 'Red Bell Pepper', 'Sweet, colourful pepper for sauces and stews.', 'Peppers', 'fresh-food', '1 kg', 2500, '🫑', 'in_stock'),
  ('fresh-yellow-bell-pepper', 'Yellow Bell Pepper', 'Bright, sweet pepper for cooking and salads.', 'Peppers', 'fresh-food', '1 kg', 2500, '🫑', 'in_stock'),
  ('fresh-scotch-bonnet', 'Scotch Bonnet (Ata Rodo)', 'Hot pepper essential for Nigerian stews and sauces.', 'Peppers', 'fresh-food', '1 kg', 3000, '🌶️', 'in_stock'),
  ('fresh-chili-pepper', 'Fresh Chili Pepper', 'Small, spicy peppers for seasoning.', 'Peppers', 'fresh-food', '1 kg', 2500, '🌶️', 'in_stock'),
  ('fresh-tatashe', 'Tatashe', 'Sweet red pepper used as the base for stews.', 'Peppers', 'fresh-food', '1 kg', 2500, '🌶️', 'in_stock'),
  ('fresh-cucumber', 'Cucumber', 'Cool, crisp cucumber for salads and snacking.', 'Salad Vegetables', 'fresh-food', '1 kg', 1500, '🥒', 'in_stock'),
  ('fresh-lettuce', 'Lettuce', 'Fresh, crisp lettuce for salads and sandwiches.', 'Salad Vegetables', 'fresh-food', '1 piece', 1500, '🥬', 'in_stock'),
  ('fresh-garden-egg', 'Garden Egg (Eggplant)', 'Traditional garden egg for snacking or sauce.', 'Fresh Vegetables', 'fresh-food', '1 kg', 1800, '🍆', 'in_stock'),
  ('fresh-okra', 'Okra', 'Fresh okra for soups and stews.', 'Fresh Vegetables', 'fresh-food', '1 kg', 2000, '🫛', 'in_stock'),
  ('fresh-green-beans', 'Green Beans', 'Crisp green beans for stir-fry and sides.', 'Fresh Vegetables', 'fresh-food', '1 kg', 2000, '🫛', 'in_stock'),
  ('fresh-peas', 'Peas', 'Sweet, tender peas for rice and stews.', 'Fresh Vegetables', 'fresh-food', '1 kg', 2500, '🫛', 'in_stock'),
  ('fresh-zucchini', 'Zucchini', 'Mild summer squash for grilling and stews.', 'Fresh Vegetables', 'fresh-food', '1 kg', 2500, '🥒', 'in_stock'),
  ('fresh-broccoli', 'Broccoli', 'Nutrient-rich vegetable for steaming and stir-fry.', 'Fresh Vegetables', 'fresh-food', '1 kg', 3000, '🥦', 'in_stock'),
  ('fresh-cauliflower', 'Cauliflower', 'Versatile vegetable for rice, soups, and roasting.', 'Fresh Vegetables', 'fresh-food', '1 piece', 2500, '🥦', 'in_stock'),
  ('fresh-sweet-corn', 'Sweet Corn', 'Sweet corn for boiling, roasting, or salads.', 'Fresh Vegetables', 'fresh-food', '1 pack', 1500, '🌽', 'in_stock'),
  ('fresh-parsley', 'Parsley', 'Fresh herb for garnish and seasoning.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-coriander', 'Coriander / Cilantro', 'Fragrant herb for garnish and sauces.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-mint', 'Mint', 'Refreshing herb for drinks and garnish.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-basil', 'Basil', 'Aromatic herb for cooking and garnish.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-rosemary', 'Rosemary', 'Fragrant herb for roasts and seasoning.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock'),
  ('fresh-celery', 'Celery', 'Crisp stalks for soups, juice, and seasoning.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1200, '🌿', 'in_stock'),
  ('fresh-scent-leaf', 'Scent Leaf', 'Aromatic Nigerian herb used in soups and pepper soup.', 'Fresh Herbs', 'fresh-food', '1 bunch', 1000, '🌿', 'in_stock')
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  section = excluded.section,
  unit = excluded.unit,
  price = excluded.price,
  image = excluded.image,
  stock_status = excluded.stock_status;
